<script setup>
import { ref, onMounted } from 'vue';
import { brandConfig } from './config/brandConfig.js';
import { useI18n } from './config/i18n.js';
import SiteHeader from './components/SiteHeader.vue';
import SiteFooter from './components/SiteFooter.vue';
import NotificationBanner from './components/NotificationBanner.vue';
import BeforeAfter from './components/BeforeAfter.vue';
import ImageRemover from './components/ImageRemover.vue';
import VideoRemover from './components/VideoRemover.vue';
import SupportPopup from './components/SupportPopup.vue';
import ParticleCanvas from './components/ParticleCanvas.vue';
import ProcessingHistory from './components/ProcessingHistory.vue';
import OnboardingTour from './components/OnboardingTour.vue';

const { t } = useI18n();
const tab = ref('image');

const activeFaq = ref(0);
function toggleFaq(index) {
  activeFaq.value = activeFaq.value === index ? null : index;
}

const faqs = [
  {
    q: 'How do I remove the Gemini AI watermark for free?',
    a: 'Using GemClean AI, the best free AI watermark remover, you can instantly erase the Google Gemini sparkle logo from any image or video. Just drag and drop your file into this browser-based tool to unwatermark Gemini creations without any cost or subscription.'
  },
  {
    q: 'How does GemClean AI remove watermarks losslessly?',
    a: 'Google Gemini adds the sparkle watermark as a deterministic transparent blend overlay. GemClean AI functions as an advanced lossless watermark removal tool by applying reverse alpha blending in WebGL. It mathematically calculates and restores the exact original pixel color values without any AI inpainting, blurring, or quality loss.'
  },
  {
    q: 'Can I remove the Gemini Veo video watermark online?',
    a: 'Yes! GemClean AI is a powerful Gemini Veo video watermark remover. It supports Veo generated MP4, WebM, and MOV videos. The video watermark removal process runs frame-by-frame entirely in your browser and preserves the original audio perfectly.'
  },
  {
    q: 'Are my photos or videos uploaded to any server?',
    a: 'Never. 100% of the computation happens locally inside your browser using client-side JavaScript & WebGL. Because it is a client-side watermark remover, your files never touch any external server or cloud, ensuring total privacy for your AI generated images.'
  },
  {
    q: 'Does it remove the transparent Gemini star logo from photos?',
    a: 'Yes, this tool specifically targets the visible transparent Gemini star logo (sparkle watermark). Whether you are using the Gemini AI photo editor or downloading from Gemini Advanced, this tool acts as the perfect Gemini transparent logo remover.'
  },
  {
    q: 'What is the difference between the visible sparkle logo and SynthID?',
    a: 'GemClean AI removes only the visible sparkle logo in the corner for clean presentation. It does not tamper with Google SynthID, which is an invisible perceptual safety cryptographic watermark embedded in Gemini AI images and Veo videos.'
  },
  {
    q: 'What is the best free Gemini AI tool to clean images?',
    a: 'For removing watermarks, GemClean AI is widely considered one of the best free Gemini AI tools. As a dedicated AI image cleaner and online AI watermark eraser, it guarantees lossless quality and instant processing.'
  },
  {
    q: 'How to batch remove watermarks from AI generated images?',
    a: 'Our tool supports bulk processing. You can select multiple PNG, JPG, or WebP files generated by Gemini Pro or Gemini Advanced, and the system will batch remove the Gemini logo from all of them instantly, outputting a convenient ZIP file.'
  }
];

// Algorithm pipeline steps
const pipelineSteps = [
  { icon: 'ph:upload-simple-bold', label: 'Decode Input', desc: 'Parse image/video file into raw RGBA pixel buffer via Canvas 2D API', color: 'pink' },
  { icon: 'ph:grid-four-bold', label: 'Locate Watermark', desc: 'Compute watermark box using resolution-adaptive geometry (48px or 96px)', color: 'cyan' },
  { icon: 'ph:wave-sine-bold', label: 'Build Alpha Map', desc: 'Generate sparkle template opacity mask from reference bg_96.png asset', color: 'purple' },
  { icon: 'ph:math-operations-bold', label: 'Reverse Blend', desc: 'Apply inverse alpha: Original = (Watermarked − α×Logo) ÷ (1−α) per channel', color: 'cyan' },
  { icon: 'ph:check-circle-bold', label: 'Export Clean', desc: 'Re-encode pristine pixels to lossless PNG or H.264 MP4 with audio passthrough', color: 'green' },
];

// Animated stats
const stats = ref([
  { value: '0ms', label: 'Upload Latency', color: 'text-neon-cyan' },
  { value: '100%', label: 'Lossless Quality', color: 'text-neon-pink' },
  { value: '0', label: 'Bytes Uploaded', color: 'text-neon-purple' },
  { value: '∞', label: 'Files / Day', color: 'text-neon-green' },
]);

const showShortcuts = ref(false);

function handleKeyDown(e) {
  if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA' || e.target.tagName === 'SELECT') return;
  
  if (e.key === '?' || (e.ctrlKey && e.key === 'k')) {
    e.preventDefault();
    showShortcuts.value = !showShortcuts.value;
  } else if (e.key === 'Escape') {
    showShortcuts.value = false;
  }
}

function scrollToTool() {
  document.getElementById('tool-section')?.scrollIntoView({ behavior: 'smooth' });
}

onMounted(() => {
  if (window.location.protocol.includes('extension') || window.location.search.includes('popup')) {
    document.documentElement.classList.add('in-extension-popup');
    document.body.classList.add('in-extension-popup');
  }
  window.addEventListener('keydown', handleKeyDown);
  const initObserver = () => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (let i = 0; i < entries.length; i++) {
          if (entries[i].isIntersecting) {
            entries[i].target.classList.add('reveal-visible');
            observer.unobserve(entries[i].target);
          }
        }
      },
      { threshold: 0.05, rootMargin: '40px' }
    );
    document.querySelectorAll('.reveal-on-scroll').forEach((el) => {
      observer.observe(el);
    });
  };
  if ('requestIdleCallback' in window) {
    requestIdleCallback(initObserver);
  } else {
    setTimeout(initObserver, 100);
  }
});
</script>

<template>
  <!-- Subtle Ambient Particle Background -->
  <ParticleCanvas />

  <!-- Ambient Light Accents -->
  <div class="fixed inset-0 overflow-hidden pointer-events-none z-0">
    <div class="absolute -top-32 -left-32 w-96 h-96 bg-neon-pink/5 rounded-full blur-3xl animate-blob"></div>
    <div class="absolute top-1/4 -right-32 w-80 h-80 bg-neon-cyan/5 rounded-full blur-3xl animate-blob animation-delay-2000"></div>
  </div>

  <div class="relative z-10 flex flex-col min-h-screen">
    <SiteHeader />
    <NotificationBanner />

    <main class="flex-grow w-full">

      <!-- ═══════════════════════════════════════════════ -->
      <!-- SECTION 1: COMPACT, TIGHT & ELEGANT HERO -->
      <!-- ═══════════════════════════════════════════════ -->
      <section class="relative flex items-center justify-center pt-6 sm:pt-10 pb-4 sm:pb-6">
        <div class="relative max-w-4xl mx-auto px-4 text-center">
          
          <!-- Badge -->
          <div class="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full neu-pill text-[11px] font-bold mb-3 sm:mb-4 reveal-on-scroll">
            <span class="relative flex h-2 w-2">
              <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-neon-pink opacity-75"></span>
              <span class="relative inline-flex rounded-full h-2 w-2 bg-neon-pink"></span>
            </span>
            <span class="text-slate-200">{{ t('heroBadge') }}</span>
            <span class="w-px h-2.5 bg-white/10"></span>
            <span class="text-neon-cyan">{{ t('heroBadgeSub') }}</span>
          </div>

          <!-- Headline -->
          <h1 class="text-2xl sm:text-4xl md:text-5xl font-extrabold tracking-tight leading-tight reveal-on-scroll">
            <span class="text-white">{{ t('heroTitle1') }}</span>
            <span class="text-transparent bg-clip-text bg-gradient-to-r from-neon-pink via-neon-purple to-neon-cyan ml-2">{{ t('heroTitle2') }}</span>
          </h1>

          <!-- Subtitle -->
          <p class="mt-2.5 sm:mt-3 text-slate-400 text-xs sm:text-base font-normal max-w-xl mx-auto leading-relaxed reveal-on-scroll">
            {{ t('heroSubtitle') }}
          </p>

          <!-- Feature Pills -->
          <div class="mt-3.5 sm:mt-4 flex flex-wrap items-center justify-center gap-2 sm:gap-3 reveal-on-scroll">
            <div class="flex items-center gap-1.5 px-3 py-1 rounded-lg neu-pill text-[11px] sm:text-xs font-semibold text-neon-cyan">
              <iconify-icon icon="ph:shield-check-fill" width="15"></iconify-icon>
              <span>{{ t('noServerUpload') }}</span>
            </div>
            <div class="flex items-center gap-1.5 px-3 py-1 rounded-lg neu-pill text-[11px] sm:text-xs font-semibold text-neon-pink">
              <iconify-icon icon="ph:image-fill" width="15"></iconify-icon>
              <span>{{ t('imageFormats') }}</span>
            </div>
            <div class="flex items-center gap-1.5 px-3 py-1 rounded-lg neu-pill text-[11px] sm:text-xs font-semibold text-neon-purple">
              <iconify-icon icon="ph:video-fill" width="15"></iconify-icon>
              <span>{{ t('videoFormats') }}</span>
            </div>
          </div>
        </div>
      </section>

      <!-- ═══════════════════════════════════════════════ -->
      <!-- SECTION 2: WORKSPACE (IMMEDIATE & PROMINENT) -->
      <!-- ═══════════════════════════════════════════════ -->
      <section id="tool-section" class="relative pt-2 pb-8 sm:pb-12">
        <div class="max-w-4xl mx-auto px-3 sm:px-6">
          <div class="neu-card cyber-card-neon rounded-2xl sm:rounded-3xl p-3.5 sm:p-5 shadow-2xl reveal-on-scroll">
            
            <!-- Sleek Tab Switcher -->
            <div class="flex justify-center mb-3 sm:mb-4">
              <div class="p-1 rounded-xl neu-inset inline-flex gap-1">
                <button
                  @click="tab = 'image'"
                  :class="[
                    'flex items-center gap-1.5 px-4 sm:px-5 py-2 rounded-lg font-bold text-xs sm:text-sm transition-all duration-200 min-h-[36px]',
                    tab === 'image'
                      ? 'bg-neu-raised text-neon-pink shadow-sm'
                      : 'text-slate-400 hover:text-white',
                  ]"
                >
                  <iconify-icon icon="ph:image-bold" width="15"></iconify-icon>
                  {{ t('tabImages') }}
                </button>
                <button
                  @click="tab = 'video'"
                  :class="[
                    'flex items-center gap-1.5 px-4 sm:px-5 py-2 rounded-lg font-bold text-xs sm:text-sm transition-all duration-200 min-h-[36px]',
                    tab === 'video'
                      ? 'bg-neu-raised text-neon-cyan shadow-sm'
                      : 'text-slate-400 hover:text-white',
                  ]"
                >
                  <iconify-icon icon="ph:video-camera-bold" width="15"></iconify-icon>
                  {{ t('tabVideos') }}
                  <span class="text-[8px] font-extrabold bg-neon-pink text-white px-1.5 py-0.2 rounded-full">{{ t('tabNew') }}</span>
                </button>
              </div>
            </div>

            <!-- Tool workspace -->
            <ImageRemover v-show="tab === 'image'" />
            <VideoRemover v-show="tab === 'video'" />
          </div>

          <!-- Inline tip -->
          <p class="text-center text-[11px] text-slate-500 mt-2.5 font-medium font-mono">
            <iconify-icon icon="ph:info" width="12" class="align-middle mr-1 text-neon-cyan"></iconify-icon>
            {{ t('tip') }}
          </p>
        </div>
      </section>

      <!-- ═══════════════════════════════════════════════ -->
      <!-- SECTION 3: BEFORE / AFTER SHOWCASE -->
      <!-- ═══════════════════════════════════════════════ -->
      <section class="py-8 sm:py-12 reveal-on-scroll">
        <div class="max-w-4xl mx-auto px-4 sm:px-6">
          <div class="text-center mb-5 sm:mb-7">
            <span class="inline-block text-[10px] font-bold uppercase tracking-widest text-neon-pink mb-1 font-mono">{{ t('realOutput') }}</span>
            <h2 class="text-xl sm:text-3xl font-extrabold text-white tracking-tight">
              {{ t('seeTheDifference') }} <span class="text-transparent bg-clip-text bg-gradient-to-r from-neon-pink to-neon-cyan">{{ t('differenceHighlight') }}</span>
            </h2>
            <p class="text-xs text-slate-400 mt-1 max-w-sm mx-auto">{{ t('sliderHint') }}</p>
          </div>

          <div class="max-w-2xl mx-auto">
            <div class="neu-card rounded-2xl p-2 sm:p-2.5 shadow-xl">
              <BeforeAfter />
            </div>
          </div>
        </div>
      </section>

      <!-- ═══════════════════════════════════════════════ -->
      <!-- SECTION 4: ALGORITHM PIPELINE -->
      <!-- ═══════════════════════════════════════════════ -->
      <section class="py-8 sm:py-12 reveal-on-scroll">
        <div class="max-w-4xl mx-auto px-4 sm:px-6">
          <div class="text-center mb-6 sm:mb-8">
            <span class="inline-block text-[10px] font-bold uppercase tracking-widest text-neon-cyan mb-1 font-mono">Architecture</span>
            <h2 class="text-xl sm:text-3xl font-extrabold text-white tracking-tight">
              {{ t('pipelineTitle') }} <span class="text-transparent bg-clip-text bg-gradient-to-r from-neon-cyan to-neon-purple">{{ t('pipelineTitleHighlight') }}</span>
            </h2>
            <p class="text-xs text-slate-400 mt-1 max-w-md mx-auto">{{ t('pipelineSubtitle') }}</p>
          </div>

          <!-- Pipeline flowchart -->
          <div class="relative max-w-2xl mx-auto">
            <div class="space-y-3 sm:space-y-3.5">
              <div
                v-for="(step, idx) in pipelineSteps"
                :key="idx"
                class="relative flex items-center gap-3 sm:gap-4 group reveal-on-scroll neu-card rounded-xl p-3 sm:p-3.5"
                :style="{ transitionDelay: (idx * 50) + 'ms' }"
              >
                <!-- Step number circle -->
                <div :class="[
                  'flex-shrink-0 w-9 h-9 sm:w-10 sm:h-10 rounded-xl flex items-center justify-center shadow-sm font-bold text-xs',
                  step.color === 'pink' ? 'bg-neon-pink/15 text-neon-pink border border-neon-pink/20' : '',
                  step.color === 'cyan' ? 'bg-neon-cyan/15 text-neon-cyan border border-neon-cyan/20' : '',
                  step.color === 'purple' ? 'bg-neon-purple/15 text-neon-purple border border-neon-purple/20' : '',
                  step.color === 'green' ? 'bg-neon-green/15 text-neon-green border border-neon-green/20' : '',
                ]">
                  <iconify-icon :icon="step.icon" width="18"></iconify-icon>
                </div>

                <!-- Step content -->
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2">
                    <span class="text-[9px] font-extrabold uppercase tracking-wider text-slate-500 font-mono">{{ t('step') }} {{ idx + 1 }}</span>
                    <h3 class="font-bold text-white text-xs sm:text-sm truncate">{{ step.label }}</h3>
                  </div>
                  <p class="text-[11px] sm:text-xs text-slate-400 mt-0.5 leading-snug font-mono">{{ step.desc }}</p>
                </div>
              </div>
            </div>
          </div>

          <!-- Formula callout -->
          <div class="max-w-2xl mx-auto mt-5 sm:mt-6 reveal-on-scroll">
            <div class="neu-card rounded-xl p-4 text-center">
              <p class="text-[10px] font-bold uppercase tracking-widest text-neon-purple mb-1.5 font-mono">{{ t('coreFormula') }}</p>
              <p class="text-sm sm:text-lg font-mono font-bold text-white tracking-tight">
                P<sub class="text-neon-green">original</sub> = ( P<sub class="text-slate-400">watermarked</sub> − α · L ) ÷ ( 1 − α )
              </p>
            </div>
          </div>
        </div>
      </section>

      <!-- ═══════════════════════════════════════════════ -->
      <!-- SECTION 5: STATS -->
      <!-- ═══════════════════════════════════════════════ -->
      <section class="py-8 sm:py-12 reveal-on-scroll">
        <div class="max-w-4xl mx-auto px-4 sm:px-6">
          <div class="grid grid-cols-2 md:grid-cols-4 gap-2.5 sm:gap-3.5">
            <div
              v-for="(stat, idx) in stats"
              :key="idx"
              class="neu-card rounded-xl p-3.5 sm:p-4 text-center"
            >
              <div :class="['text-xl sm:text-2xl font-black counter-animate', stat.color]">
                {{ stat.value }}
              </div>
              <div class="text-[10px] sm:text-[11px] font-bold text-slate-500 uppercase tracking-wider mt-0.5 font-mono">{{ stat.label }}</div>
            </div>
          </div>
        </div>
      </section>

      <!-- ═══════════════════════════════════════════════ -->
      <!-- SECTION 6: PROCESSING HISTORY -->
      <!-- ═══════════════════════════════════════════════ -->
      <ProcessingHistory />

      <!-- ═══════════════════════════════════════════════ -->
      <!-- SECTION 7: FAQ -->
      <!-- ═══════════════════════════════════════════════ -->
      <section class="py-8 sm:py-12 reveal-on-scroll">
        <div class="max-w-3xl mx-auto px-4 sm:px-6">
          <div class="text-center mb-5 sm:mb-7">
            <span class="inline-block text-[10px] font-bold uppercase tracking-widest text-neon-purple mb-1 font-mono">{{ t('faqSupport') }}</span>
            <h2 class="text-xl sm:text-3xl font-extrabold text-white tracking-tight">
              {{ t('faqTitle') }} <span class="text-transparent bg-clip-text bg-gradient-to-r from-neon-pink to-neon-purple">{{ t('faqTitleHighlight') }}</span>
            </h2>
          </div>

          <div class="space-y-2.5">
            <div
              v-for="(faq, idx) in faqs"
              :key="idx"
              class="neu-card rounded-xl overflow-hidden"
            >
              <button
                @click="toggleFaq(idx)"
                class="w-full p-3.5 sm:p-4 flex items-center justify-between font-bold text-xs sm:text-sm text-white hover:text-neon-pink transition-colors text-left min-h-[44px]"
              >
                <span class="pr-3">{{ faq.q }}</span>
                <iconify-icon
                  icon="ph:caret-down-bold"
                  width="14"
                  :class="['transition-transform duration-200 text-neon-pink flex-shrink-0', activeFaq === idx ? 'rotate-180' : '']"
                ></iconify-icon>
              </button>
              <div
                v-show="activeFaq === idx"
                class="px-3.5 pb-3.5 sm:px-4 sm:pb-4 text-xs sm:text-sm text-slate-300 leading-relaxed border-t border-white/5 pt-2.5 animate-fade-in font-normal"
              >
                {{ faq.a }}
              </div>
            </div>
          </div>
        </div>
      </section>

    </main>

    <SiteFooter />
    <SupportPopup />

    <!-- Keyboard Shortcuts Floating Button -->
    <button
      @click="showShortcuts = true"
      class="fixed bottom-3.5 left-3.5 z-40 neu-pill px-2.5 py-1.5 rounded-lg text-xs font-bold text-slate-400 hover:text-neon-cyan flex items-center gap-1.5 transition-all min-h-[34px]"
      title="Keyboard Shortcuts (? or Ctrl+K)"
    >
      <iconify-icon icon="ph:keyboard-bold" width="14"></iconify-icon>
      <span class="hidden sm:inline">{{ t('shortcuts') }}</span>
      <kbd class="px-1 py-0.2 text-[9px] font-mono bg-white/5 rounded">?</kbd>
    </button>

    <!-- Keyboard Shortcuts Modal -->
    <div
      v-if="showShortcuts"
      class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 animate-fade-in backdrop-blur-xs"
      @click.self="showShortcuts = false"
    >
      <div class="neu-card rounded-2xl p-5 max-w-sm w-full shadow-2xl">
        <div class="flex items-center justify-between border-b border-white/5 pb-2.5 mb-3">
          <h3 class="font-bold text-white text-sm flex items-center gap-2">
            <iconify-icon icon="ph:keyboard-bold" class="text-neon-cyan"></iconify-icon>
            {{ t('keyboardShortcuts') }}
          </h3>
          <button @click="showShortcuts = false" class="text-slate-400 hover:text-white p-1 rounded-lg">
            <iconify-icon icon="ph:x-bold" width="16"></iconify-icon>
          </button>
        </div>

        <div class="space-y-2 text-xs font-medium">
          <div class="flex justify-between items-center p-2.5 rounded-lg neu-inset">
            <span>{{ t('pasteImage') }}</span>
            <kbd class="px-2 py-0.5 font-mono font-bold bg-neon-pink/15 text-neon-pink rounded">Ctrl + V</kbd>
          </div>
          <div class="flex justify-between items-center p-2.5 rounded-lg neu-inset">
            <span>{{ t('toggleShortcuts') }}</span>
            <div class="flex gap-1 items-center">
              <kbd class="px-1.5 py-0.5 font-mono font-bold bg-neon-pink/15 text-neon-pink rounded">?</kbd>
              <span class="text-slate-500 text-[10px]">or</span>
              <kbd class="px-1.5 py-0.5 font-mono font-bold bg-neon-pink/15 text-neon-pink rounded">Ctrl + K</kbd>
            </div>
          </div>
          <div class="flex justify-between items-center p-2.5 rounded-lg neu-inset">
            <span>{{ t('closeModal') }}</span>
            <kbd class="px-2 py-0.5 font-mono font-bold bg-neon-pink/15 text-neon-pink rounded">Esc</kbd>
          </div>
        </div>
      </div>
    </div>

    <!-- Onboarding Tour -->
    <OnboardingTour />
  </div>
</template>